const SCHOLARS = [
  /* ── Plato ──────────────────────────────────────────── */
  {
    name: 'Alice Merton',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Postdoctoral Research Fellow',
    focus: 'Plato', ancients: ['Plato'],
    tags: ['metaphysics', 'epistemology'],
    email: 'a.merton@philosophy.ox.ac.uk', web: '', links: [],
    photo: '',
  },
  {
    name: 'Priya Sharma',
    uni: "King's College London", dept: 'Department of Philosophy',
    city: 'London', position: 'Lecturer',
    focus: 'Plato', ancients: ['Plato'],
    tags: ['politics', 'ethics'],
    email: '', web: '', links: [],
    photo: '',
  },
  {
    name: 'Tom Ellison',
    uni: 'University of Edinburgh', dept: 'School of Philosophy, Psychology and Language Sciences',
    city: 'Edinburgh', position: 'Postdoctoral Research Fellow',
    focus: 'Plato', ancients: ['Plato', 'Socrates'],
    tags: ['politics', 'metaphysics'],
    email: '', web: '', links: [],
    photo: '',
  },

  /* ── Aristotle ───────────────────────────────────────── */
  {
    name: 'Clara Hughes',
    uni: 'University of Bristol', dept: 'Department of Philosophy',
    city: 'Bristol', position: 'Lecturer',
    focus: 'Aristotle', ancients: ['Aristotle'],
    tags: ['mind', 'ethics'],
    email: '', web: '', links: [],
    photo: '',
  },
  {
    name: 'Daniel Park',
    uni: 'University College London', dept: 'Department of Philosophy',
    city: 'London', position: 'Postdoctoral Research Fellow',
    focus: 'Aristotle', ancients: ['Aristotle'],
    tags: ['ethics', 'politics'],
    email: '', web: '', links: [],
    photo: '',
  },
  {
    name: 'Fatima Al-Rashid',
    uni: 'University of Manchester', dept: 'Department of Classics, Ancient History and Archaeology',
    city: 'Manchester', position: 'Lecturer',
    focus: 'Aristotle', ancients: ['Aristotle'],
    tags: ['language', 'epistemology'],
    email: '', web: '', links: [],
    photo: '',
  },
  {
    name: 'Marcus Webb',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Lecturer',
    focus: 'Aristotle', ancients: ['Aristotle'],
    tags: ['language', 'mind'],
    email: '', web: '', links: [],
    photo: '',
  },

  /* ── Hellenistic ─────────────────────────────────────── */
  {
    name: 'Cristóbal Zarzar',
    uni: 'University of Cambridge', dept: 'Faculty of Classics',
    city: 'Cambridge', position: 'Postdoctoral Research Fellow',
    focus: 'Hellenistic', ancients: ['Stoicism', 'Academic Scepticism', 'Epicureanism'],
    tags: ['epistemology', 'mind', 'ethics'],
    email: 'cz298@cam.ac.uk',
    web: 'https://czarzar.com',
    links: [
      { label: 'Faculty page', url: 'https://www.classics.cam.ac.uk/staff/dr-cristobal-zarzar' },
      { label: 'College page', url: 'https://www.clarehall.cam.ac.uk/directory/cristobal-zarzar/' },
    ],
    photo: 'https://www.classics.cam.ac.uk/sites/default/files/styles/inline/public/images/profile/cz.jpg',
  },
  {
    name: 'David M. Douglas',
    uni: 'University of Cambridge', dept: 'Faculty of Classics',
    city: 'Cambridge', position: 'Research Fellow',
    focus: 'Hellenistic', ancients: ['Epicureanism', 'Philodemus of Gadara'],
    tags: ['ethics', 'epistemology', 'language'],
    email: 'dmd48@cam.ac.uk',
    web: '',
    links: [
      { label: 'Faculty page', url: 'https://www.classics.cam.ac.uk/staff/david-m-douglas' },
      { label: 'College page', url: 'https://www.emma.cam.ac.uk/people/dr-david-douglas' },
    ],
    photo: 'https://res.cloudinary.com/dspfaec6d/image/upload/v1777030653/david-douglas.jpg',
  },
  {
    name: 'Isabelle Roy',
    uni: 'University of Leeds', dept: 'School of Philosophy, Religion and History of Science',
    city: 'Leeds', position: 'PhD Researcher',
    focus: 'Hellenistic', ancients: ['Stoicism', 'Pyrrhonian Scepticism'],
    tags: ['ethics', 'epistemology'],
    email: '', web: '', links: [],
    photo: '',
  },
  {
    name: 'James Chen',
    uni: 'University of Warwick', dept: 'Department of Philosophy',
    city: 'Coventry', position: 'Lecturer',
    focus: 'Hellenistic', ancients: ['Stoicism'],
    tags: ['ethics', 'politics'],
    email: '', web: '', links: [],
    photo: '',
  },
  {
    name: 'Keisha Bright',
    uni: 'University of Edinburgh', dept: 'School of Philosophy, Psychology and Language Sciences',
    city: 'Edinburgh', position: 'PhD Researcher',
    focus: 'Hellenistic', ancients: ['Epicureanism', 'Stoicism'],
    tags: ['ethics', 'mind'],
    email: '', web: '', links: [],
    photo: '',
  },
  {
    name: 'Lena Kovač',
    uni: 'University of Nottingham', dept: 'Department of Philosophy',
    city: 'Nottingham', position: 'Postdoctoral Research Fellow',
    focus: 'Hellenistic', ancients: ['Academic Scepticism', 'Pyrrhonian Scepticism'],
    tags: ['epistemology', 'language'],
    email: '', web: '', links: [],
    photo: '',
  },
  {
    name: 'Yemi Adeyemi',
    uni: 'Birkbeck, University of London', dept: 'Department of Philosophy',
    city: 'London', position: 'PhD Researcher',
    focus: 'Hellenistic', ancients: ['Epicureanism'],
    tags: ['language', 'ethics'],
    email: '', web: '', links: [],
    photo: '',
  },

  /* ── Pre-Socratics ───────────────────────────────────── */
  {
    name: 'George Okafor',
    uni: 'University of Glasgow', dept: 'School of Humanities',
    city: 'Glasgow', position: 'Lecturer',
    focus: 'Pre-Socratics', ancients: ['Heraclitus', 'Parmenides'],
    tags: ['metaphysics', 'language'],
    email: '', web: '', links: [],
    photo: '',
  },
  {
    name: 'Helena Voss',
    uni: 'Durham University', dept: 'Department of Philosophy',
    city: 'Durham', position: 'Postdoctoral Research Fellow',
    focus: 'Pre-Socratics', ancients: ['Parmenides', 'Democritus'],
    tags: ['metaphysics', 'epistemology'],
    email: '', web: '', links: [],
    photo: '',
  },

  /* ── New Cambridge entries ───────────────────────────── */
  {
    name: 'Chiara Martini',
    uni: 'University of Cambridge', dept: 'Faculty of Classics',
    city: 'Cambridge', position: 'Early Career Research Fellow in Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle'],
    tags: ['metaphysics', 'mind'],
    email: 'cm2266@cam.ac.uk',
    web: 'https://chiaramartini.eu',
    links: [
      { label: 'Faculty page', url: 'https://www.classics.cam.ac.uk/staff/dr-chiara-martini-0' },
      { label: 'College page', url: 'https://www.corpus.cam.ac.uk/people/dr-chiara-martini' },
    ],
    photo: 'https://res.cloudinary.com/dspfaec6d/image/upload/v1777030280/chiara-martini.jpg',
  },
  {
    name: 'Lea Cantor',
    uni: 'University of Cambridge', dept: 'Faculty of Classics',
    city: 'Cambridge', position: 'Blacker Loewe Research Fellow in Philosophy',
    focus: 'Pre-Socratics', ancients: ['Parmenides', 'Pyrrhonian Scepticism'],
    tags: ['epistemology', 'metaphysics'],
    email: 'lc840@cam.ac.uk',
    web: 'https://leacantor.com/index.html',
    links: [
      { label: 'Faculty page', url: 'https://www.classics.cam.ac.uk/staff/dr-lea-cantor' },
      { label: 'College page', url: 'https://www.pet.cam.ac.uk/person/cantor' },
    ],
    photo: 'https://res.cloudinary.com/dspfaec6d/image/upload/v1777030280/lea-cantor.jpg',
  },
  {
    name: 'Christian Keime',
    uni: 'University of Cambridge', dept: 'Faculty of Classics',
    city: 'Cambridge', position: 'Teaching Associate in Classics (Greek and Roman Philosophy)',
    focus: 'Plato', ancients: ['Plato', 'Socrates'],
    tags: ['epistemology', 'ethics', 'metaphysics'],
    email: 'ck643@cam.ac.uk',
    web: '',
    links: [
      { label: 'Faculty page', url: 'https://www.classics.cam.ac.uk/directory/dr-christian-keime' },
    ],
    photo: 'https://res.cloudinary.com/dspfaec6d/image/upload/v1777030281/christian-keime.png',
  },
  {
    name: 'James Warren',
    uni: 'University of Cambridge', dept: 'Faculty of Classics',
    city: 'Cambridge', position: 'Professor of Ancient Philosophy',
    focus: 'Hellenistic', ancients: ['Epicureanism'],
    tags: ['ethics', 'epistemology', 'mind'],
    email: 'jiw1001@cam.ac.uk',
    web: '',
    links: [
      { label: 'Faculty page', url: 'https://www.classics.cam.ac.uk/directory/james-warren' },
      { label: 'College page', url: 'https://www.corpus.cam.ac.uk/people/professor-james-warren' },
    ],
    photo: 'https://res.cloudinary.com/dspfaec6d/image/upload/v1777030281/james-warren.jpg',
  },
  {
    name: 'Laura M. Castelli',
    uni: 'University of Cambridge', dept: 'Faculty of Classics',
    city: 'Cambridge', position: 'Associate Professor in Classics (Greek and Roman Philosophy)',
    focus: 'Aristotle', ancients: ['Aristotle', 'Alexander of Aphrodisias'],
    tags: ['metaphysics', 'language', 'epistemology'],
    email: 'lc918@cam.ac.uk',
    web: 'https://lauramcastelli.com/',
    links: [
      { label: 'Faculty page', url: 'https://www.classics.cam.ac.uk/staff/dr-laura-m-castelli-0' },
      { label: 'College page', url: 'https://www.clarehall.cam.ac.uk/directory/castelli/' },
    ],
    photo: 'https://res.cloudinary.com/dspfaec6d/image/upload/v1777030279/laura-castelli.jpg',
  },
  {
    name: 'Gábor Betegh',
    uni: 'University of Cambridge', dept: 'Faculty of Classics',
    city: 'Cambridge', position: 'Laurence Professor of Ancient Philosophy',
    focus: 'Pre-Socratics', ancients: ['Heraclitus', 'Parmenides', 'Democritus'],
    tags: ['metaphysics', 'epistemology'],
    email: 'gb230@cam.ac.uk',
    web: '',
    links: [
      { label: 'Faculty page', url: 'https://www.classics.cam.ac.uk/directory/professor-gabor-betegh' },
      { label: 'College page', url: 'https://www.christs.cam.ac.uk/college/people/fellows/professor-gabor-betegh' },
    ],
    photo: 'https://res.cloudinary.com/dspfaec6d/image/upload/v1777030279/gabor-betegh.jpg',
  },
  {
    name: 'Myrto Hatzimichali',
    uni: 'University of Cambridge', dept: 'Faculty of Classics',
    city: 'Cambridge', position: 'Senior Lecturer in Classics (Ancient Philosophy)',
    focus: 'Aristotle', ancients: ['Aristotle', 'Alexander of Aphrodisias'],
    tags: ['metaphysics', 'language', 'mind'],
    email: 'mh303@cam.ac.uk',
    web: '',
    links: [
      { label: 'Faculty page', url: 'https://www.classics.cam.ac.uk/directory/myrto-hatzimichali' },
      { label: 'College page', url: 'https://www.homerton.cam.ac.uk/people/myrto-hatzimichali' },
    ],
    photo: 'https://res.cloudinary.com/dspfaec6d/image/upload/v1777030278/myrto-hatzimichali.jpg',
  },
  {
    name: 'Frisbee C.C. Sheffield',
    uni: 'University of Cambridge', dept: 'Faculty of Classics',
    city: 'Cambridge', position: 'Associate Professor of Classics',
    focus: 'Plato', ancients: ['Plato', 'Socrates'],
    tags: ['ethics', 'mind', 'metaphysics'],
    email: 'fccs2@cam.ac.uk',
    web: '',
    links: [
      { label: 'Faculty page', url: 'https://www.classics.cam.ac.uk/directory/dr-frisbee-c-c-sheffield' },
      { label: 'College page', url: 'https://www.dow.cam.ac.uk/people/dr-frisbee-sheffield' },
    ],
    photo: 'https://res.cloudinary.com/dspfaec6d/image/upload/v1777030278/frisbee-sheffield.jpg',
  },

  /* ── UCL ──────────────────────────────────────────────── */
  {
    name: 'Fiona Leigh',
    uni: 'University College London', dept: 'Department of Philosophy',
    city: 'London', position: 'Professor of Ancient Greek Philosophy',
    focus: 'Plato', ancients: ['Plato', 'Socrates'],
    tags: ['metaphysics', 'epistemology', 'mind'],
    email: 'fiona.leigh@ucl.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://profiles.ucl.ac.uk/4084-fiona-leigh' }],
    photo: '',
  },
  {
    name: 'Mark Eli Kalderon',
    uni: 'University College London', dept: 'Department of Philosophy',
    city: 'London', position: 'Professor of Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle', 'Empedocles'],
    tags: ['metaphysics', 'mind', 'epistemology'],
    email: '', web: '',
    links: [{ label: 'Faculty page', url: 'https://profiles.ucl.ac.uk/6364-mark-kalderon' }],
    photo: '',
  },
  {
    name: 'Andrew Gregory',
    uni: 'University College London', dept: 'Department of Science and Technology Studies',
    city: 'London', position: 'Professor of History and Philosophy of Science',
    focus: 'Pre-Socratics', ancients: ['Heraclitus', 'Parmenides', 'Anaximander'],
    tags: ['metaphysics', 'epistemology'],
    email: 'andrew.gregory@ucl.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://profiles.ucl.ac.uk/4876-andrew-gregory' }],
    photo: '',
  },
  {
    name: 'Elena Cagnoli Fiecconi',
    uni: 'University College London', dept: 'Department of Greek and Latin',
    city: 'London', position: 'Associate Professor in Ancient Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle'],
    tags: ['ethics', 'mind'],
    email: 'e.fiecconi@ucl.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://profiles.ucl.ac.uk/30436-elena-cagnoli-fiecconi' }],
    photo: '',
  },
  {
    name: 'Simona Aimar',
    uni: 'University College London', dept: 'Department of Philosophy',
    city: 'London', position: 'Lecturer in Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle'],
    tags: ['metaphysics', 'language'],
    email: '', web: 'https://www.simonaimar.com',
    links: [],
    photo: '',
  },
  {
    name: 'Michael McOsker',
    uni: 'University College London', dept: 'Department of Greek and Latin',
    city: 'London', position: 'Researcher in Papyrology',
    focus: 'Hellenistic', ancients: ['Epicureanism', 'Philodemus of Gadara'],
    tags: ['language', 'epistemology'],
    email: '', web: '',
    links: [{ label: 'Faculty page', url: 'https://profiles.ucl.ac.uk/97051-michael-mcosker/about' }],
    photo: '',
  },

  /* ── KCL ──────────────────────────────────────────────── */
  {
    name: 'Peter Adamson',
    uni: "King's College London", dept: 'Department of Philosophy',
    city: 'London', position: 'Professor of Ancient and Medieval Philosophy',
    focus: 'Hellenistic', ancients: ['Neoplatonism', 'Stoicism'],
    tags: ['metaphysics', 'mind'],
    email: 'peter.adamson@kcl.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.kcl.ac.uk/people/peter-adamson' }],
    photo: '',
  },
  {
    name: 'Joachim Aufderheide',
    uni: "King's College London", dept: 'Department of Philosophy',
    city: 'London', position: 'Reader in Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle', 'Plato'],
    tags: ['ethics', 'metaphysics'],
    email: 'joachim.aufderheide@kcl.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.kcl.ac.uk/people/joachim-aufderheide' }],
    photo: '',
  },
  {
    name: 'Shaul Tor',
    uni: "King's College London", dept: 'Departments of Classics and Philosophy',
    city: 'London', position: 'Reader in Ancient Philosophy',
    focus: 'Pre-Socratics', ancients: ['Heraclitus', 'Parmenides', 'Xenophanes'],
    tags: ['epistemology', 'metaphysics'],
    email: '', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.kcl.ac.uk/people/shaul-tor' }],
    photo: '',
  },

  /* ── Royal Holloway ───────────────────────────────────── */
  {
    name: 'Elizabeth Gloyn',
    uni: 'Royal Holloway, University of London', dept: 'Department of Classics',
    city: 'London', position: 'Reader in Latin Language and Literature',
    focus: 'Hellenistic', ancients: ['Stoicism'],
    tags: ['ethics', 'politics'],
    email: '',
    web: '',
    links: [{ label: 'Faculty page', url: 'https://pure.royalholloway.ac.uk/en/persons/elizabeth-gloyn/' }],
    photo: 'https://pure.royalholloway.ac.uk/files-asset/32788341/1T3A9961_25_percent.jpg',
  },
  {
    name: 'John Sellars',
    uni: 'Royal Holloway, University of London', dept: 'Department of Philosophy',
    city: 'London', position: 'Reader in History of Philosophy',
    focus: 'Hellenistic', ancients: ['Stoicism', 'Epicureanism'],
    tags: ['ethics', 'metaphysics'],
    email: '', web: 'http://www.johnsellars.org.uk',
    links: [{ label: 'Faculty page', url: 'https://pure.royalholloway.ac.uk/portal/en/persons/john-sellars(709b3ed0-efe1-45cc-923f-9d180a42fb9a).html' }],
    photo: '',
  },
  {
    name: 'David Preston',
    uni: 'Royal Holloway, University of London', dept: 'Department of Politics, International Relations and Philosophy',
    city: 'London', position: 'Lecturer in Philosophy',
    focus: 'Pre-Socratics', ancients: ['Socrates', 'Empedocles'],
    tags: ['ethics', 'epistemology'],
    email: '',
    web: '',
    links: [{ label: 'Faculty page', url: 'https://pure.royalholloway.ac.uk/en/persons/david-preston/' }],
    photo: 'https://pure.royalholloway.ac.uk/files-asset/45727336/69329786_10100254463854564_1106066203136229376_n.jpg',
  },

  /* ── Oxford ───────────────────────────────────────────── */
  {
    name: 'Alexander Bown',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Fellow and Tutor in Ancient Philosophy',
    focus: 'Hellenistic', ancients: ['Stoicism', 'Academic Scepticism'],
    tags: ['epistemology', 'language', 'metaphysics'],
    email: 'alexander.bown@philosophy.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://onap.web.ox.ac.uk/people/alexander-bown' }],
    photo: '',
  },
  {
    name: 'Luca Castagnoli',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Associate Professor of Ancient Greek Philosophy',
    focus: 'Hellenistic', ancients: ['Pyrrhonian Scepticism', 'Academic Scepticism'],
    tags: ['epistemology', 'language'],
    email: 'luca.castagnoli@philosophy.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://onap.web.ox.ac.uk/people/luca-castagnoli' }],
    photo: '',
  },
  {
    name: 'Ursula Coope',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Professor of Ancient Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle'],
    tags: ['metaphysics', 'mind', 'ethics'],
    email: 'ursula.coope@philosophy.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://onap.web.ox.ac.uk/people/ursula-coope' }],
    photo: '',
  },
  {
    name: 'Lindsay Judson',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Emeritus Professor of Ancient Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle', 'Plato'],
    tags: ['metaphysics', 'epistemology'],
    email: 'lindsay.judson@philosophy.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://onap.web.ox.ac.uk/people/lindsay-judson' }],
    photo: '',
  },
  {
    name: 'Paolo Fait',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Anthony Quinton Fellow; Tutor in Classical Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle'],
    tags: ['metaphysics', 'language', 'epistemology'],
    email: 'paolo.fait@philosophy.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://onap.web.ox.ac.uk/people/paolo-fait' }],
    photo: '',
  },
  {
    name: 'Marion Durand',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Associate Professor of Ancient Philosophy',
    focus: 'Hellenistic', ancients: ['Stoicism'],
    tags: ['language', 'epistemology'],
    email: 'marion.durand@philosophy.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://onap.web.ox.ac.uk/people/marion-durand' }],
    photo: '',
  },
  {
    name: 'Roger Crisp',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Professor of Moral Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle', 'Plato'],
    tags: ['ethics', 'politics'],
    email: 'roger.crisp@st-annes.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://onap.web.ox.ac.uk/people/roger-crisp' }],
    photo: '',
  },
  {
    name: 'Karen Margrethe Nielsen',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Professor of Ancient Greek and Roman Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle', 'Plato'],
    tags: ['ethics', 'mind', 'politics'],
    email: 'karen.nielsen@some.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://onap.web.ox.ac.uk/people/karen-margrethe-nielsen' }],
    photo: '',
  },
  {
    name: 'Michail Peramatzis',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Hinton Clarendon Fellow in Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle', 'Plato'],
    tags: ['metaphysics', 'epistemology'],
    email: 'michail.peramatzis@philosophy.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://onap.web.ox.ac.uk/people/michail-peramatzis' }],
    photo: '',
  },
  {
    name: 'Tobias Reinhardt',
    uni: 'University of Oxford', dept: 'Faculty of Classics',
    city: 'Oxford', position: 'Corpus Christi Professor of the Latin Language and Literature',
    focus: 'Hellenistic', ancients: ['Stoicism', 'Academic Scepticism'],
    tags: ['epistemology', 'language'],
    email: 'tobias.reinhardt@classics.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://onap.web.ox.ac.uk/people/tobias-reinhardt' }],
    photo: '',
  },
  {
    name: 'Dominic Scott',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Professor of Philosophy',
    focus: 'Plato', ancients: ['Plato', 'Aristotle'],
    tags: ['ethics', 'epistemology', 'politics'],
    email: 'dominic.scott@philosophy.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://onap.web.ox.ac.uk/people/dominic-scott' }],
    photo: '',
  },
  {
    name: 'Simon Shogry',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Associate Professor of Philosophy',
    focus: 'Hellenistic', ancients: ['Stoicism'],
    tags: ['epistemology', 'ethics', 'mind'],
    email: 'simon.shogry@philosophy.ox.ac.uk', web: 'https://simonshogry.com',
    links: [{ label: 'Faculty page', url: 'https://onap.web.ox.ac.uk/people/simon-shogry' }],
    photo: '',
  },
  {
    name: 'Stefan Sienkiewicz',
    uni: 'University of Oxford', dept: 'Faculty of Philosophy',
    city: 'Oxford', position: 'Departmental Lecturer in Ancient Philosophy',
    focus: 'Hellenistic', ancients: ['Pyrrhonian Scepticism', 'Academic Scepticism'],
    tags: ['epistemology'],
    email: 'stefan.sienkiewicz@queens.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://onap.web.ox.ac.uk/people/stefan-sienkiewicz' }],
    photo: '',
  },
  {
    name: 'Ugo Zilioli',
    uni: 'University of Oxford', dept: 'Faculty of Theology and Religion',
    city: 'Oxford', position: 'John Fell Fund Researcher',
    focus: 'Pre-Socratics', ancients: ['Protagoras', 'Pyrrhonian Scepticism'],
    tags: ['metaphysics', 'epistemology'],
    email: 'ugo.zilioli@theology.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.theology.ox.ac.uk/people/ugo-zilioli' }],
    photo: '',
  },
  {
    name: 'Jan Westerhoff',
    uni: 'University of Oxford', dept: 'Faculty of Theology and Religion',
    city: 'Oxford', position: 'Professor of Buddhist Philosophy',
    focus: 'Pre-Socratics', ancients: ['Neoplatonism'],
    tags: ['metaphysics', 'epistemology'],
    email: 'jan.westerhoff@lmh.ox.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.theology.ox.ac.uk/people/professor-jan-westerhoff' }],
    photo: '',
  },

  /* ── Nottingham ───────────────────────────────────────── */
  {
    name: 'Matthew Duncombe',
    uni: 'University of Nottingham', dept: 'Department of Philosophy',
    city: 'Nottingham', position: 'Associate Professor in Philosophy',
    focus: 'Aristotle', ancients: ['Plato', 'Aristotle'],
    tags: ['epistemology', 'language', 'metaphysics'],
    email: 'matthew.duncombe@nottingham.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.nottingham.ac.uk/humanities/departments/philosophy/people/matthew.duncombe' }],
    photo: 'https://www.nottingham.ac.uk/humanities/departments/philosophy/people/staff-images/matthewduncombe.jpg',
  },

  /* ── Edinburgh ────────────────────────────────────────── */
  {
    name: 'Benjamin Harriman',
    uni: 'University of Edinburgh', dept: 'School of History, Classics and Archaeology',
    city: 'Edinburgh', position: 'Lecturer in Greek Literature and Philosophy',
    focus: 'Hellenistic', ancients: ['Stoicism', 'Pyrrhonian Scepticism'],
    tags: ['metaphysics', 'mind', 'epistemology'],
    email: 'Benjamin.Harriman@ed.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://edwebprofiles.ed.ac.uk/profile/benjamin-harriman' }],
    photo: 'https://edwebprofiles.ed.ac.uk/sites/default/files/styles/uoe_profile_picture/public/profilepicture_1.jpg',
  },
  {
    name: 'Simon Trépanier',
    uni: 'University of Edinburgh', dept: 'School of History, Classics and Archaeology',
    city: 'Edinburgh', position: 'Senior Lecturer in Classics',
    focus: 'Pre-Socratics', ancients: ['Empedocles', 'Parmenides'],
    tags: ['metaphysics', 'epistemology'],
    email: 'Simon.Trepanier@ed.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://edwebprofiles.ed.ac.uk/profile/simon-trepanier' }],
    photo: 'https://edwebprofiles.ed.ac.uk/sites/default/files/styles/uoe_profile_picture/public/simon_trepanier.jpg',
  },

  /* ── Essex ────────────────────────────────────────────── */
  {
    name: 'Ellisif Wasmuth',
    uni: 'University of Essex', dept: 'School of Philosophical, Historical and Interdisciplinary Studies',
    city: 'Colchester', position: 'Lecturer in Philosophy',
    focus: 'Plato', ancients: ['Plato', 'Socrates'],
    tags: ['epistemology', 'mind'],
    email: 'ellisif.wasmuth@essex.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.essex.ac.uk/people/WASMU56501/Ellisif-Wasmuth' }],
    photo: 'http://www1.essex.ac.uk/people-images/WASMU56501.jpg',
  },

  /* ── Kent ─────────────────────────────────────────────── */
  {
    name: 'Kelli Rudolph',
    uni: 'University of Kent', dept: 'Department of Classical and Archaeological Studies',
    city: 'Canterbury', position: 'Senior Lecturer in Classics and Philosophy',
    focus: 'Pre-Socratics', ancients: ['Heraclitus', 'Democritus', 'Parmenides'],
    tags: ['epistemology', 'metaphysics'],
    email: '', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.kent.ac.uk/classics-archaeology/people/1741/rudolph-kelli' }],
    photo: '',
  },

  /* ── Warwick ──────────────────────────────────────────── */
  {
    name: 'Curie Virag',
    uni: 'University of Warwick', dept: 'Department of Philosophy',
    city: 'Coventry', position: 'Associate Professor in World Philosophies',
    focus: 'Pre-Socratics', ancients: ['Socrates'],
    tags: ['ethics', 'mind', 'politics'],
    email: '', web: '',
    links: [{ label: 'Faculty page', url: 'https://warwick.ac.uk/fac/soc/philosophy/people/virag/' }],
    photo: '',
  },

  /* ── St Andrews ───────────────────────────────────────── */
  {
    name: 'Margaret Hampson',
    uni: 'University of St Andrews', dept: 'Department of Philosophy',
    city: 'St Andrews', position: 'Lecturer in Ancient Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle'],
    tags: ['ethics', 'mind'],
    email: 'mrh8@st-andrews.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.st-andrews.ac.uk/philosophy/people/mrh8/' }],
    photo: 'https://portal.st-andrews.ac.uk/staff-photos/mrh8/medium',
  },
  {
    name: 'Alex Long',
    uni: 'University of St Andrews', dept: 'School of Classics',
    city: 'St Andrews', position: 'Professor',
    focus: 'Plato', ancients: ['Plato', 'Stoicism'],
    tags: ['ethics', 'epistemology', 'politics'],
    email: 'agl10@st-andrews.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.st-andrews.ac.uk/classics/people/agl10/' }],
    photo: 'https://portal.st-andrews.ac.uk/staff-photos/agl10/medium',
  },

  /* ── Durham ───────────────────────────────────────────── */
  {
    name: 'Phillip Horky',
    uni: 'Durham University', dept: 'Department of Classics and Ancient History',
    city: 'Durham', position: 'Professor of Ancient Philosophy',
    focus: 'Pre-Socratics', ancients: ['Parmenides', 'Democritus'],
    tags: ['metaphysics', 'politics', 'epistemology'],
    email: 'phillip.horky@durham.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.durham.ac.uk/staff/phillip-horky/' }],
    photo: '',
  },
  {
    name: 'Giulia Bonasio',
    uni: 'Durham University', dept: 'Department of Classics and Ancient History',
    city: 'Durham', position: 'Associate Professor in Ancient Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle', 'Plato'],
    tags: ['ethics', 'epistemology', 'mind'],
    email: '', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.durham.ac.uk/staff/giulia-bonasio/' }],
    photo: '',
  },
  {
    name: 'Nathan Gilbert',
    uni: 'Durham University', dept: 'Department of Classics and Ancient History',
    city: 'Durham', position: 'Associate Professor in Classics and Ancient History',
    focus: 'Hellenistic', ancients: ['Epicureanism', 'Stoicism'],
    tags: ['ethics', 'politics'],
    email: '', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.durham.ac.uk/staff/nathan-b-gilbert/' }],
    photo: '',
  },

  /* ── Southampton ──────────────────────────────────────── */
  {
    name: 'Bradford Jean-Hyuk Kim',
    uni: 'University of Southampton', dept: 'Department of Philosophy',
    city: 'Southampton', position: 'Lecturer in Philosophy',
    focus: 'Aristotle', ancients: ['Aristotle'],
    tags: ['ethics', 'politics'],
    email: 'b.kim@soton.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.southampton.ac.uk/people/65djlr/doctor-bradford-kim' }],
    photo: '',
  },

  /* ── Manchester ───────────────────────────────────────── */
  {
    name: 'Jenny Bryan',
    uni: 'University of Manchester', dept: 'Department of Classics and Ancient History',
    city: 'Manchester', position: 'Senior Lecturer in Classical Philosophy',
    focus: 'Pre-Socratics', ancients: ['Parmenides', 'Empedocles'],
    tags: ['epistemology', 'metaphysics'],
    email: '', web: '',
    links: [{ label: 'Faculty page', url: 'https://research.manchester.ac.uk/en/persons/jenny.bryan' }],
    photo: '',
  },

  /* ── Cambridge (additional) ───────────────────────────── */
  {
    name: 'Carol Atack',
    uni: 'University of Cambridge', dept: 'Faculty of Classics',
    city: 'Cambridge', position: 'Bye-Fellow and Director of Studies in Classics',
    focus: 'Plato', ancients: ['Plato', 'Socrates'],
    tags: ['politics', 'epistemology'],
    email: '', web: '',
    links: [
      { label: 'Faculty page', url: 'https://www.classics.cam.ac.uk/directory/dr-carol-atack' },
      { label: 'College page', url: 'https://newn.cam.ac.uk/person/carol-atack' },
    ],
    photo: '',
  },
  {
    name: 'Yumi Suzuki',
    uni: 'University of Cambridge', dept: 'Faculty of Classics',
    city: 'Cambridge', position: 'Research Fellow',
    focus: 'Pre-Socratics', ancients: ['Socrates', 'Plato'],
    tags: ['metaphysics', 'epistemology'],
    email: 'ys747@cam.ac.uk', web: '',
    links: [{ label: 'Faculty page', url: 'https://www.classics.cam.ac.uk/staff/yumi-suzuki' }],
    photo: '',
  },
  {
    name: 'Jingyi Jenny Zhao',
    uni: 'University of Cambridge', dept: 'Needham Research Institute',
    city: 'Cambridge', position: 'ISF Senior Research Fellow',
    focus: 'Pre-Socratics', ancients: ['Socrates', 'Plato'],
    tags: ['ethics', 'politics'],
    email: '', web: 'https://www.jingyizhao.com',
    links: [{ label: 'College page', url: 'https://www.clarehall.cam.ac.uk/directory/zhao/' }],
    photo: 'https://images.squarespace-cdn.com/content/v1/66b7a23b2de837612be1a16d/21e7d803-35d8-449e-a2f0-f47f22ec74c8/DSC_0540.jpeg',
  },
];

/* ── Philosopher / specialism cards ─────────────────────
   key         must match 'focus' values in SCHOLARS
   subsections must match values in SCHOLARS.ancients
   img         public-domain image URL                   */
const PHILOSOPHERS = [
  {
    key: 'Plato', label: 'Plato', dates: 'c. 428–348 BCE',
    blurb: 'Republic, Phaedo, Symposium',
    subsections: ['Socrates', 'Plato'],
    img: 'https://commons.wikimedia.org/wiki/Special:FilePath/Plato_Silanion_Musei_Capitolini_MC1377.jpg?width=320',
  },
  {
    key: 'Aristotle', label: 'Aristotle', dates: '384–322 BCE',
    blurb: 'Metaphysics, Nicomachean Ethics, Politics',
    subsections: ['Aristotle', 'Alexander of Aphrodisias'],
    img: 'https://commons.wikimedia.org/wiki/Special:FilePath/Aristotle_Altemps_Inv8575.jpg?width=320',
  },
  {
    key: 'Hellenistic', label: 'Hellenistic philosophy', dates: 'c. 323–31 BCE',
    blurb: 'Stoics, Epicureans, Sceptics',
    subsections: ['Stoicism', 'Epicureanism', 'Pyrrhonian Scepticism', 'Academic Scepticism', 'Philodemus of Gadara', 'Neoplatonism'],
    img: 'https://commons.wikimedia.org/wiki/Special:FilePath/MSR-ra-1-Zeno_of_Citium.jpg?width=320',
  },
  {
    key: 'Pre-Socratics', label: 'Pre-Socratic philosophy', dates: 'c. 600–400 BCE',
    blurb: 'Heraclitus, Parmenides, Democritus',
    subsections: ['Heraclitus', 'Parmenides', 'Democritus', 'Empedocles', 'Anaxagoras'],
    img: 'https://commons.wikimedia.org/wiki/Special:FilePath/Raffael_058.jpg?width=320',
  },
];

/* ── Map coordinates ── add new cities here as needed ── */
const UNI_COORDS = {
  Edinburgh:   { lat: 55.9445, lng: -3.1892 },
  Glasgow:     { lat: 55.8714, lng: -4.2882 },
  Durham:      { lat: 54.7740, lng: -1.5782 },
  'St Andrews':{ lat: 56.3398, lng: -2.7967 },
  Leeds:       { lat: 53.8067, lng: -1.5550 },
  Manchester:  { lat: 53.4668, lng: -2.2339 },
  Nottingham:  { lat: 52.9382, lng: -1.1974 },
  Coventry:    { lat: 52.3838, lng: -1.5603 },
  Cambridge:   { lat: 52.2043, lng:  0.1149 },
  Oxford:      { lat: 51.7548, lng: -1.2544 },
  London:      { lat: 51.5074, lng: -0.1278 },
  Bristol:     { lat: 51.4584, lng: -2.6032 },
  Southampton: { lat: 50.9340, lng: -1.3967 },
  Canterbury:  { lat: 51.2802, lng:  1.0789 },
  Colchester:  { lat: 51.8893, lng:  0.9040 },
};

/* ── Research theme tag styles ── */
const THEMES = {
  metaphysics:  { label: 'Metaphysics',       bg: '#eceaf6', txt: '#2a2260' },
  ethics:       { label: 'Ethics',            bg: '#e2f2ea', txt: '#0e4a2e' },
  epistemology: { label: 'Epistemology',       bg: '#fdf2e2', txt: '#6b3800' },
  mind:         { label: 'Phil. of mind',     bg: '#fce8ef', txt: '#6b0030' },
  politics:     { label: 'Political phil.',   bg: '#e2edf8', txt: '#0b3860' },
  language:     { label: 'Language & logic',  bg: '#e8f4e3', txt: '#1a4808' },
};

/* Ancient tags — warm terracotta, distinct from theme tags */
const ANCT = { bg: '#f5ede2', txt: '#6b3a10' };

/* Network colours */
const FOCUS_HEX   = { 'Plato':'#3d3480', 'Aristotle':'#1a6b52', 'Hellenistic':'#8a4218', 'Pre-Socratics':'#575350' };
const FOCUS_LIGHT = { 'Plato':'#eceaf6', 'Aristotle':'#e2f2ea', 'Hellenistic':'#f4ece3', 'Pre-Socratics':'#ececec' };
